baseURL = "https://475300.github.io/"
languageCode = "zh-cn"
title = "乐土为家"
pluralizelisttitles = "false"
hasCJKLanguage = "true"
theme = ["the-roots-home", "hugo-easy-gallery"]
[Params]
Description = "enel ♥ sajiner"
[taxonomies]
category = "categories"
tag = "tags"
author = "authors"