# netlify cms
backend:
  name: github
  repo: 475300/475300.github.io
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/img"

collections:
  - name: "日记本"
    label: "日记本"
    folder: "content/日记本"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["enel", "sajiner"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "交易"
    label: "交易"
    folder: "content/交易"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["enel", "sajiner"], default: "enel"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "交易日志"
    label: "交易日志"
    folder: "content/交易日志"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["enel", "sajiner"], default: "enel"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "食谱"
    label: "食谱"
    folder: "content/食谱"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["enel", "sajiner"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "未分类"
    label: "未分类"
    folder: "content/未分类"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["enel", "sajiner"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
    